---
active_modules: [pygments, tags, blog, latex, XresourcesLexer, disqus]
author: Thomas Gläßle
blogtitle: "cat /dev/brain |"
canonical_url: https://www.coldfix.de
ignore_files:
  - '.*'
  - '_*'
  - '*.conf'
  - '*.pyc'
  - '*.pdl'
  - 'config.yml'
  - 'Makefile'
  - 'README.rst'
  - 'LICENSE.rst'
  - 'TODO'
  - '*.aux'
  - '*.log'
  - 'Dockerfile'
  - 'blogdown'
modules:
  pygments:
    style: monokai
  disqus:
    shortname: coldfix-de

feed:
  name: Coder Gone Mad
  subtitle: Tales of Code Gone Bad

flattr_id: Kanarienmaus
