---
active_modules: [pygments, tags, blog, latex]
author: Thomas Gläßle
blogtitle: "cat /dev/brain |"
canonical_url: http://www.coldfix.de
modules:
  pygments:
    style: tango

flattr_id: Kanarienmaus
