---
active_modules: [pygments, tags, blog, latex, XresourcesLexer]
author: Thomas Gläßle
blogtitle: "cat /dev/brain |"
canonical_url: http://www.coldfix.de
ignore_files:
  - '.*'
  - '_*'
  - '*.conf'
  - '*.pyc'
  - '*.pdl'
  - 'config.yml'
  - 'Makefile'
  - 'README.rst'
  - 'LICENSE.rst'
  - 'TODO'
modules:
  pygments:
    style: monokai

flattr_id: Kanarienmaus
