#! /usr/bin/env python
# encoding: utf-8

"""
Get link by text content.

Usage:
    hrefbytext URL TEXT

Example:
    hrefbytext "http://ctan.org/pkg/subcaption" \
               "Pack&shy;age doc&shy;u&shy;men&shy;ta&shy;tion"
"""

import sys
from lxml.html import parse, fromstring


def main(args):
    url = args[0]
    doc = parse(url).getroot()
    text = fromstring(args[1]).text_content()   # replace HTML entities
    for link in doc.cssselect('a'):
        if link.text_content() == text:
            print(link.get('href'))


if __name__ == '__main__':
    main(sys.argv[1:])
